---
title: "MI of Agreeableness Across Gender"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(lavaan)
library(semPlot)
library(rio)
library(here)

knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}

big6 <- import(here("aggregated_data.Rdata"))
```


```{r agreeableness configural}
# Configural Invariance 
configural_a<- '
  agree =~ aloof_R + kind + fault_R
'
  
  configural_fitted_a <- cfa(configural_a,
               data = big6,
               group = "Gender"
 )

summary(configural_fitted_a, fit.measures = TRUE, standardized = TRUE)
```

```{r agreeableness metric}
# Metric Invariance 
metric_fitted_a <- cfa(configural_a,
               group.equal = "loadings",
               data = big6,
               group = "Gender"
 )

summary(metric_fitted_a, fit.measures = TRUE, standardized = TRUE)

fitmeasures(configural_fitted_a, c("cfi", "mfi"))
fitmeasures(metric_fitted_a, c("cfi", "mfi"))

modindices(metric_fitted_a)
lavTestScore(metric_fitted_a)


```

```{r agreeableness strong}
# Strong Invariance 
 strong_fitted_a <- cfa(configural_a,
               group.equal = c("loadings", "intercepts"),
               data = big6,
               group = "Gender"
 )

summary(strong_fitted_a, fit.measures = TRUE, standardized = TRUE)

fitmeasures(metric_fitted_a, c("cfi", "mfi"))
fitmeasures(strong_fitted_a, c("cfi", "mfi"))

modindices(strong_fitted_a)
lavTestScore(strong_fitted_a)

```

```{r agreeableness strict}
# Strict Invariance
strict_fitted_a <- cfa(configural_a,
               group.equal = c("loadings", "intercepts", "residuals"),
               data = big6,
               group = "Gender"
 )

summary(strict_fitted_a, fit.measures = TRUE, standardized = T)

fitmeasures(strong_fitted_a, c("cfi", "mfi"))
fitmeasures(strict_fitted_a, c("cfi", "mfi"))

modindices(strict_fitted_a)
lavTestScore(strict_fitted_a)

```

