---
title: "MI of Openness Across Gender"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(lavaan)
library(semPlot)
library(rio)
library(here)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r load data}

big6 <- import(here("aggregated_data.Rdata"))
```

```{r o configural}
# Configural Invariance 
configural_o<- '
  open =~ original + noart_R + reflect
'
  
  configural_fitted_o <- cfa(configural_o,
               data = big6,
               group = "Gender"
 )

summary(configural_fitted_o, fit.measures = TRUE, standardized = TRUE)
```

```{r o metric}
# Metric Invariance 
metric_fitted_o <- cfa(configural_o,
               group.equal = "loadings",
               data = big6,
               group = "Gender"
 )

summary(metric_fitted_o, fit.measures = TRUE, standardized = TRUE)

fitmeasures(configural_fitted_o, c("cfi", "mfi"))
fitmeasures(metric_fitted_o, c("cfi", "mfi"))

modindices(metric_fitted_o)
lavTestScore(metric_fitted_o)


```

```{r o strong}
# Strong Invariance 
 strong_fitted_o <- cfa(configural_o,
               group.equal = c("loadings", "intercepts"),
               data = big6,
               group = "Gender"
 )

summary(strong_fitted_o, fit.measures = TRUE, standardized = TRUE)

fitmeasures(metric_fitted_o, c("cfi", "mfi"))
fitmeasures(strong_fitted_o, c("cfi", "mfi"))

modindices(strong_fitted_o)
lavTestScore(strong_fitted_o)

```
```{r o strong partial}
# Strong Partial Invariance 
 strong_fitted_p_o <- cfa(configural_o,
               group.equal = c("loadings", "intercepts"),
               group.partial = c("noart_R ~ 1"),
               data = big6,
               group = "Gender"
 )

summary(strong_fitted_p_o, fit.measures = TRUE, standardized = TRUE)

fitmeasures(strong_fitted_o, c("cfi", "mfi"))
fitmeasures(strong_fitted_p_o, c("cfi", "mfi"))

```

```{r o strict}
# Strict Partial Invariance 
strict_fitted_p_o <- cfa(configural_o,
               group.equal = c("loadings", "intercepts", "residuals"),
               group.partial = c("noart_R ~ 1", "noart_R ~~ noart_R"),
               data = big6,
               group = "Gender"
 )

summary(strict_fitted_p_o, fit.measures = TRUE, standardized = T)

fitmeasures(strict_fitted_p_o, c("cfi", "mfi"))
fitmeasures(strict_fitted_p_o, c("cfi", "mfi"))

```